contentgrid:
  gateway:
    runtime-platform:
      enabled: true

testing:
  bootstrap:
    enable: false

spring:
  main:
    cloud-platform: kubernetes # bypass detection this is running on K8S
  cloud:
    gateway:
      routes:
        - id: app
          uri: cg://ignored
          predicates:
            - ApplicationId=

servicediscovery:
  namespace: default
  enabled: true
