contentgrid:
  gateway:
    runtime-platform:
      enabled: true
      catalog:
        route-uses-server-port: true # temporary workaround - not needed in production

testing:
  bootstrap:
    enable: false

spring:
  main:
    cloud-platform: kubernetes # bypass detection this is running on K8S
  cloud:
    gateway:
      routes:
        - id: root
          uri: https://ignored
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /me

servicediscovery:
  namespace: default
  enabled: true
