server:
  forward-headers-strategy: native

logging.level:
  reactor.netty.http.server.AccessLog: INFO

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader
            - TokenRelay
            - Abac
          trusted-proxies: 10\..*\..*\..*

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
  otlp:
    metrics:
      export:
        enabled: false

contentgrid:
  gateway:
    user-info:
      enabled: false
      path: /me
  configuration.discovery.kubernetes:
    enabled: "${contentgrid.gateway.runtime-platform.enabled:false}"
