server:
  forward-headers-strategy: native


spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - PreserveHostHeader
        - TokenRelay
        - Abac

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
