server:
  forward-headers-strategy: native

logging.level:
  reactor.netty.http.server.AccessLog: INFO

spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - PreserveHostHeader
        - TokenRelay
        - Abac

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

contentgrid:
  gateway:
    user-info:
      enabled: false
      path: /me