spring:
  security:
    oauth2:

      # OIDC login
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://${DOCKER_HOST_IP:172.17.0.1}:8090/realms/contentcloud-gateway
        registration:
          keycloak:
            client-id: contentcloud-gateway
            client-secret: d6a59786-ea91-4b7d-892f-eb3426b4d8cb
            scope:
              - openid
              - profile
              - email

      # JWT Bearer authentication
      resourceserver:
        jwt:
          issuer-uri: http://${DOCKER_HOST_IP:172.17.0.1}:8090/realms/contentcloud-gateway