version: '3.7'

services:


  tempo:
    image: grafana/tempo:latest@sha256:1ce31d6d7ffab62189685e8c47881d4a561c5d38bd0dbd66e40ca83cef07923d
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tracing/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"   # tempo

  grafana:
    image: grafana/grafana:13.2.0@sha256:3fd54ae1214669f8355f065ec9f6445d5279a3d77095ab048ca045685272429b
    volumes:
      - ./tracing/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"

  otelcol:
      image: otel/opentelemetry-collector:latest@sha256:e495787f07dbe432ce763ebaf5bc3d113850e9eee2250ade7a3da6a882d0d69a
      volumes:
        - ./tracing/otelconfig.yaml:/etc/otelcol/config.yaml
      ports:
        - 4318:4318

  gateway:
    environment:
      - "MANAGEMENT_TRACING_ENABLED=TRUE"
      - "MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0"
      - "MANAGEMENT_OTLP_TRACING_ENDPOINT=http://otelcol:4318/v1/traces"
      - "MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED=FALSE"

volumes:
    tempo-data:

