name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'
      - name: Build and Test
        run: ./gradlew check --info
      - name: Sonar Analysis
        run: ./gradlew jacocoTestReport sonar --info
        if: env.SONAR_TOKEN != null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Publish docker image
        if: ${{ github.ref == 'refs/heads/main' || startswith(github.ref, 'refs/tags/') }}
        run: ./gradlew bootBuildImage --publishImage
        env:
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_URL: ghcr.io
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_USERNAME: ${{ github.actor }}
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
