name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Build and Test
        run: ./gradlew check --info
      - name: Sonar Analysis
        run: ./gradlew sonar --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Publish docker image
        if: ${{ github.ref == 'refs/heads/main' || startswith(github.ref, 'refs/tags/') }}
        run: ./gradlew bootBuildImage --publishImage
        env:
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_URL: docker.xenit.eu
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_USERNAME: ${{ secrets.CLOUDSMITH_USER }}
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_PASSWORD: ${{ secrets.CLOUDSMITH_APIKEY }}
