name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 8 * * 5" # runs at 8AM UTC every Friday
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    name: "Update Gradle Wrapper"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          team-reviewers: '@xenit-eu/contentgrid'
